version: '3.8'
services:
  db:
    image: mysql:5.7
    container_name: sk-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123x
      MYSQL_DATABASE: sk_db
      MYSQL_USER: bruker1
      MYSQL_PASSWORD: abc123x
    volumes:
      - db_data:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    container_name: sk-wordpress
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: bruker1
      WORDPRESS_DB_PASSWORD: abc123x
      WORDPRESS_DB_NAME: sk_db
    volumes:
      - wp_data:/var/www/html
volumes:
    db_data:
      driver: local
    wp_data:
      driver: local